list: $/moonwalkerz/gestio/models/comune/columns.yaml
modelClass: MoonWalkerz\Gestio\Models\Comune
title: Comuni
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'moonwalkerz/gestio/comuni/update/:id'
